version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
    volumes:
      - ./:/app
    restart: unless-stopped
